# Generated by Django 4.2.7 on 2023-11-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
